# Generated by Django 6.0.4 on 2026-04-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialization',
            new_name='specialty',
        ),
        migrations.AddField(
            model_name='doctor',
            name='availability',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
